### ISSUE TITLE
Why not use the `openjdk:8-jdk-alpine` docker image?

### ISSUE THREAD

**Issue by crooy** [chook/docker-takipi#4]
You are doing a lot of work to install java in alpine... which is already solved by the official image `openjdk:8-jdk-alpine`

**Comment by chook** [comment]
Hi Roland - thanks for commenting. 

If you look again at the Dockerfile you'll notice we are forcing **Oracle JDK** and not Alpine OpenJDK. This is because currently Takipi (now named OverOps) is complied against glibc and not musl, so it must ran inside a glibc jvm.
